use crate::target_ir::TargetIr;

pub fn generate_cli_js(target: &TargetIr) -> String {
  let mut out = String::new();
  let target_json = serde_json::to_string(target).unwrap_or_else(|_| "{}".to_string());

  out.push_str("// Auto-generated by sculpt (cli)\n\n");
  out.push_str(&format!("const TARGET = {};\n\n", target_json));
  out.push_str("const VIEWS = TARGET.views || {};\n");
  out.push_str("const FLOW = TARGET.flow || { start: '', transitions: {} };\n");
  out.push_str("let state = FLOW.start || '';\n\n");

  out.push_str("const COLORS = {\n");
  out.push_str("  black: '\\x1b[30m', red: '\\x1b[31m', green: '\\x1b[32m', yellow: '\\x1b[33m',\n");
  out.push_str("  blue: '\\x1b[34m', magenta: '\\x1b[35m', cyan: '\\x1b[36m', white: '\\x1b[37m'\n");
  out.push_str("};\n");
  out.push_str("const RESET = '\\x1b[0m';\n\n");

  out.push_str("function render() {\n");
  out.push_str("  console.clear();\n");
  out.push_str("  const items = VIEWS[state] || [];\n");
  out.push_str("  for (const item of items) {\n");
  out.push_str("    if (item.kind === 'text') {\n");
  out.push_str("      const color = item.color ? (COLORS[item.color] || '') : '';\n");
  out.push_str("      console.log(color + (item.text || '') + RESET);\n");
  out.push_str("    }\n");
  out.push_str("  }\n");
  out.push_str("}\n\n");

  out.push_str("function dispatch(event) {\n");
  out.push_str("  const before = state;\n");
  out.push_str("  const map = (FLOW.transitions && FLOW.transitions[state]) || {};\n");
  out.push_str("  if (map[event]) state = map[event];\n");
  out.push_str("  if (state !== before) render();\n");
  out.push_str("}\n\n");

  out.push_str("function normalizeKey(key) {\n");
  out.push_str("  if (key === '\\r') return 'enter';\n");
  out.push_str("  if (key === '\\u001b') return 'esc';\n");
  out.push_str("  if (key === ' ') return 'space';\n");
  out.push_str("  return key.trim().toLowerCase();\n");
  out.push_str("}\n\n");

  out.push_str("render();\n");
  out.push_str("if (process.stdin.isTTY) process.stdin.setRawMode(true);\n");
  out.push_str("process.stdin.resume();\n");
  out.push_str("process.stdin.on('data', (buf) => {\n");
  out.push_str("  const key = buf.toString('utf8');\n");
  out.push_str("  if (key === '\\u0003') process.exit(0);\n");
  out.push_str("  const k = normalizeKey(key);\n");
  out.push_str("  dispatch(`key(${k})`);\n");
  out.push_str("});\n");

  out
}
