use crate::target_ir::TargetIr;

pub fn generate_cli_js(target: &TargetIr) -> String {
    let mut out = String::new();
    let target_json = serde_json::to_string(target).unwrap_or_else(|_| "{}".to_string());

    out.push_str("// Auto-generated by sculpt (cli)\n\n");
    out.push_str(&format!("const TARGET = {};\n\n", target_json));
    out.push_str("const VIEWS = TARGET.views || {};\n");
    out.push_str("const FLOW = TARGET.flow || { start: '', transitions: {} };\n");
    out.push_str("let state = FLOW.start || '';\n\n");
    out.push_str("const fs = require('fs');\n");
    out.push_str("const path = require('path');\n\n");
    out.push_str("const EXT = TARGET.extensions || {};\n");
    out.push_str(
        "const RUNTIME_RULES = Array.isArray(EXT.runtimeRules) ? EXT.runtimeRules : [];\n",
    );
    out.push_str("const RUNTIME_STATE = (TARGET.state && typeof TARGET.state === 'object') ? JSON.parse(JSON.stringify(TARGET.state)) : {};\n");

    out.push_str("const COLORS = {\n");
    out.push_str(
        "  black: '\\x1b[30m', red: '\\x1b[31m', green: '\\x1b[32m', yellow: '\\x1b[33m',\n",
    );
    out.push_str(
        "  blue: '\\x1b[34m', magenta: '\\x1b[35m', cyan: '\\x1b[36m', white: '\\x1b[37m'\n",
    );
    out.push_str("};\n");
    out.push_str("const RESET = '\\x1b[0m';\n\n");

    out.push_str("function inferBuiltinGame() {\n");
    out.push_str("  if (EXT && EXT.game && EXT.game.kind) return EXT.game;\n");
    out.push_str("  const texts = [];\n");
    out.push_str("  for (const items of Object.values(VIEWS)) {\n");
    out.push_str("    for (const item of items || []) {\n");
    out.push_str("      if (item && item.kind === 'text' && typeof item.text === 'string') texts.push(item.text.toUpperCase());\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("  const hasPlayState = !!(FLOW.transitions && FLOW.transitions.Play);\n");
    out.push_str(
        "  const isBreakout = texts.some((t) => t.includes('BREAKOUT')) && hasPlayState;\n",
    );
    out.push_str("  if (isBreakout) {\n");
    out.push_str("    return {\n");
    out.push_str("      kind: 'breakout',\n");
    out.push_str("      width: Number(RUNTIME_STATE.width || 42),\n");
    out.push_str("      height: Number(RUNTIME_STATE.height || 22),\n");
    out.push_str("      paddleWidth: Number(RUNTIME_STATE.paddleWidth || 7),\n");
    out.push_str("      tickMs: Number(RUNTIME_STATE.speedMs || 60),\n");
    out.push_str("      lives: Number(RUNTIME_STATE.lives || 3),\n");
    out.push_str("      brickRows: 5,\n");
    out.push_str("      brickCols: 8,\n");
    out.push_str("      brickWidth: 4,\n");
    out.push_str("      gap: 1\n");
    out.push_str("    };\n");
    out.push_str("  }\n");
    out.push_str("  const isSnake = texts.some((t) => t.includes('SNAKE')) && hasPlayState;\n");
    out.push_str("  if (isSnake) {\n");
    out.push_str("    return {\n");
    out.push_str("      kind: 'snake',\n");
    out.push_str("      width: Number(RUNTIME_STATE.width || RUNTIME_STATE.boardWidth || 28),\n");
    out.push_str(
        "      height: Number(RUNTIME_STATE.height || RUNTIME_STATE.boardHeight || 16),\n",
    );
    out.push_str("      tickMs: Number(RUNTIME_STATE.speedMs || 120)\n");
    out.push_str("    };\n");
    out.push_str("  }\n");
    out.push_str("  return null;\n");
    out.push_str("}\n\n");

    out.push_str("const GAME_SPEC = inferBuiltinGame();\n");
    out.push_str("let game = null;\n");
    out.push_str("let tickHandle = null;\n\n");

    out.push_str("function createBreakout(spec) {\n");
    out.push_str("  const width = Math.max(30, Number(spec.width || 42));\n");
    out.push_str("  const height = Math.max(16, Number(spec.height || 22));\n");
    out.push_str("  const paddleWidth = Math.max(3, Number(spec.paddleWidth || 7));\n");
    out.push_str("  const lives = Math.max(1, Number(spec.lives || 3));\n");
    out.push_str("  const brickRows = Math.max(1, Number(spec.brickRows || 5));\n");
    out.push_str("  const brickCols = Math.max(2, Number(spec.brickCols || 8));\n");
    out.push_str("  const brickWidth = Math.max(2, Number(spec.brickWidth || 4));\n");
    out.push_str("  const gap = Math.max(0, Number(spec.gap || 1));\n");
    out.push_str("  const innerWidth = width - 2;\n");
    out.push_str("  const totalBricksWidth = brickCols * brickWidth + (brickCols - 1) * gap;\n");
    out.push_str(
        "  const leftPad = Math.max(1, Math.floor((innerWidth - totalBricksWidth) / 2));\n",
    );
    out.push_str("  const bricks = [];\n");
    out.push_str("  for (let r = 0; r < brickRows; r += 1) {\n");
    out.push_str("    for (let c = 0; c < brickCols; c += 1) {\n");
    out.push_str("      bricks.push({ x: 1 + leftPad + c * (brickWidth + gap), y: 2 + r, w: brickWidth, alive: true });\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("  const paddleY = height - 2;\n");
    out.push_str("  const paddleX = Math.floor((width - paddleWidth) / 2);\n");
    out.push_str("  return {\n");
    out.push_str("    width,\n");
    out.push_str("    height,\n");
    out.push_str("    paddleWidth,\n");
    out.push_str("    paddleY,\n");
    out.push_str("    paddleX,\n");
    out.push_str("    ballX: paddleX + Math.floor(paddleWidth / 2),\n");
    out.push_str("    ballY: paddleY - 1,\n");
    out.push_str("    vx: 1,\n");
    out.push_str("    vy: -1,\n");
    out.push_str("    launched: false,\n");
    out.push_str("    score: 0,\n");
    out.push_str("    lives,\n");
    out.push_str("    won: false,\n");
    out.push_str("    bricks,\n");
    out.push_str("    tickMs: Math.max(20, Number(spec.tickMs || 60))\n");
    out.push_str("  };\n");
    out.push_str("}\n\n");

    out.push_str("function createSnake(spec) {\n");
    out.push_str("  const width = Math.max(10, Number(spec.width || 16));\n");
    out.push_str("  const height = Math.max(8, Number(spec.height || 12));\n");
    out.push_str("  const cx = Math.floor(width / 2);\n");
    out.push_str("  const cy = Math.floor(height / 2);\n");
    out.push_str("  const snake = [\n");
    out.push_str("    { x: cx, y: cy },\n");
    out.push_str("    { x: cx - 1, y: cy },\n");
    out.push_str("    { x: cx - 2, y: cy }\n");
    out.push_str("  ];\n");
    out.push_str("  const s = {\n");
    out.push_str("    kind: 'snake',\n");
    out.push_str("    width,\n");
    out.push_str("    height,\n");
    out.push_str("    tickMs: Math.max(40, Number(spec.tickMs || 120)),\n");
    out.push_str("    snake,\n");
    out.push_str("    direction: 'right',\n");
    out.push_str("    pendingDirection: 'right',\n");
    out.push_str("    score: 0,\n");
    out.push_str("    alive: true,\n");
    out.push_str("    food: null\n");
    out.push_str("  };\n");
    out.push_str("  s.food = placeFood(s);\n");
    out.push_str("  return s;\n");
    out.push_str("}\n\n");

    out.push_str("function placeFood(s) {\n");
    out.push_str("  const occ = new Set(s.snake.map((p) => `${p.x},${p.y}`));\n");
    out.push_str("  const free = [];\n");
    out.push_str("  for (let y = 1; y < s.height - 1; y += 1) {\n");
    out.push_str("    for (let x = 1; x < s.width - 1; x += 1) {\n");
    out.push_str("      const key = `${x},${y}`;\n");
    out.push_str("      if (!occ.has(key)) free.push({ x, y });\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("  if (free.length === 0) return null;\n");
    out.push_str("  return free[Math.floor(Math.random() * free.length)];\n");
    out.push_str("}\n\n");

    out.push_str("function enterPlayState() {\n");
    out.push_str("  if (!GAME_SPEC) return;\n");
    out.push_str("  if (GAME_SPEC.kind === 'breakout') {\n");
    out.push_str("    game = createBreakout(GAME_SPEC);\n");
    out.push_str("  } else if (GAME_SPEC.kind === 'snake') {\n");
    out.push_str("    game = createSnake(GAME_SPEC);\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    out.push_str("function ensureGameInit() {\n");
    out.push_str("  if (!GAME_SPEC || game) return;\n");
    out.push_str("  enterPlayState();\n");
    out.push_str("}\n\n");

    out.push_str("function resetBall() {\n");
    out.push_str("  game.ballX = game.paddleX + Math.floor(game.paddleWidth / 2);\n");
    out.push_str("  game.ballY = game.paddleY - 1;\n");
    out.push_str("  game.vx = game.vx >= 0 ? 1 : -1;\n");
    out.push_str("  game.vy = -1;\n");
    out.push_str("  game.launched = false;\n");
    out.push_str("}\n\n");

    out.push_str("function stepBreakout() {\n");
    out.push_str("  if (!game || game.kind !== 'breakout' || state !== 'Play') return;\n");
    out.push_str("  if (!game.launched) {\n");
    out.push_str("    game.ballX = game.paddleX + Math.floor(game.paddleWidth / 2);\n");
    out.push_str("    game.ballY = game.paddleY - 1;\n");
    out.push_str("    return;\n");
    out.push_str("  }\n");
    out.push_str("  let nx = game.ballX + game.vx;\n");
    out.push_str("  let ny = game.ballY + game.vy;\n");
    out.push_str("  if (nx <= 1 || nx >= game.width - 2) {\n");
    out.push_str("    game.vx *= -1;\n");
    out.push_str("    nx = game.ballX + game.vx;\n");
    out.push_str("  }\n");
    out.push_str("  if (ny <= 1) {\n");
    out.push_str("    game.vy *= -1;\n");
    out.push_str("    ny = game.ballY + game.vy;\n");
    out.push_str("  }\n");
    out.push_str("  if (ny >= game.height - 1) {\n");
    out.push_str("    game.lives -= 1;\n");
    out.push_str("    if (game.lives <= 0) {\n");
    out.push_str("      dispatch('done');\n");
    out.push_str("      return;\n");
    out.push_str("    }\n");
    out.push_str("    resetBall();\n");
    out.push_str("    return;\n");
    out.push_str("  }\n");
    out.push_str("  if (game.vy > 0 && ny === game.paddleY - 1 && nx >= game.paddleX && nx < game.paddleX + game.paddleWidth) {\n");
    out.push_str("    const center = game.paddleX + (game.paddleWidth - 1) / 2;\n");
    out.push_str("    const offset = nx - center;\n");
    out.push_str("    game.vx = offset < 0 ? -1 : 1;\n");
    out.push_str("    if (offset === 0) game.vx = Math.random() < 0.5 ? -1 : 1;\n");
    out.push_str("    game.vy = -1;\n");
    out.push_str("    ny = game.ballY + game.vy;\n");
    out.push_str("  }\n");
    out.push_str("  let hitBrick = false;\n");
    out.push_str("  for (const b of game.bricks) {\n");
    out.push_str("    if (!b.alive) continue;\n");
    out.push_str("    if (ny === b.y && nx >= b.x && nx < b.x + b.w) {\n");
    out.push_str("      b.alive = false;\n");
    out.push_str("      game.score += 10;\n");
    out.push_str("      game.vy *= -1;\n");
    out.push_str("      hitBrick = true;\n");
    out.push_str("      ny = game.ballY + game.vy;\n");
    out.push_str("      break;\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("  if (!hitBrick && game.bricks.every((b) => !b.alive)) {\n");
    out.push_str("    game.won = true;\n");
    out.push_str("    dispatch('done');\n");
    out.push_str("    return;\n");
    out.push_str("  }\n");
    out.push_str("  game.ballX = nx;\n");
    out.push_str("  game.ballY = ny;\n");
    out.push_str("}\n\n");

    out.push_str("function handleGameInput(event) {\n");
    out.push_str("  if (!game || state !== 'Play') return;\n");
    out.push_str(
        "  if (game.kind === 'breakout' && (event === 'key(a)' || event === 'key(left)')) {\n",
    );
    out.push_str("    game.paddleX = Math.max(1, game.paddleX - 2);\n");
    out.push_str("  } else if (game.kind === 'breakout' && (event === 'key(d)' || event === 'key(right)')) {\n");
    out.push_str(
        "    game.paddleX = Math.min(game.width - 1 - game.paddleWidth, game.paddleX + 2);\n",
    );
    out.push_str("  } else if (game.kind === 'breakout' && event === 'key(space)') {\n");
    out.push_str("    game.launched = true;\n");
    out.push_str("  } else if (game.kind === 'snake') {\n");
    out.push_str("    if ((event === 'key(w)' || event === 'key(up)') && game.direction !== 'down') game.pendingDirection = 'up';\n");
    out.push_str("    if ((event === 'key(s)' || event === 'key(down)') && game.direction !== 'up') game.pendingDirection = 'down';\n");
    out.push_str("    if ((event === 'key(a)' || event === 'key(left)') && game.direction !== 'right') game.pendingDirection = 'left';\n");
    out.push_str("    if ((event === 'key(d)' || event === 'key(right)') && game.direction !== 'left') game.pendingDirection = 'right';\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    out.push_str("function renderBreakout() {\n");
    out.push_str("  const grid = Array.from({ length: game.height }, () => Array.from({ length: game.width }, () => ' '));\n");
    out.push_str("  for (let x = 0; x < game.width; x += 1) { grid[0][x] = '#'; grid[game.height - 1][x] = '#'; }\n");
    out.push_str("  for (let y = 0; y < game.height; y += 1) { grid[y][0] = '#'; grid[y][game.width - 1] = '#'; }\n");
    out.push_str("  for (const b of game.bricks) {\n");
    out.push_str("    if (!b.alive) continue;\n");
    out.push_str("    for (let x = b.x; x < b.x + b.w; x += 1) grid[b.y][x] = '=';\n");
    out.push_str("  }\n");
    out.push_str("  for (let x = game.paddleX; x < game.paddleX + game.paddleWidth; x += 1) grid[game.paddleY][x] = '_';\n");
    out.push_str("  if (game.ballY > 0 && game.ballY < game.height - 1 && game.ballX > 0 && game.ballX < game.width - 1) {\n");
    out.push_str("    grid[game.ballY][game.ballX] = 'o';\n");
    out.push_str("  }\n");
    out.push_str(
        "  console.log(COLORS.cyan + `Score: ${game.score}   Lives: ${game.lives}` + RESET);\n",
    );
    out.push_str("  for (const row of grid) console.log(row.join(''));\n");
    out.push_str("}\n\n");

    out.push_str("function stepSnake() {\n");
    out.push_str(
        "  if (!game || game.kind !== 'snake' || state !== 'Play' || !game.alive) return;\n",
    );
    out.push_str("  game.direction = game.pendingDirection || game.direction;\n");
    out.push_str("  const head = game.snake[0];\n");
    out.push_str("  let nx = head.x;\n");
    out.push_str("  let ny = head.y;\n");
    out.push_str("  if (game.direction === 'up') ny -= 1;\n");
    out.push_str("  if (game.direction === 'down') ny += 1;\n");
    out.push_str("  if (game.direction === 'left') nx -= 1;\n");
    out.push_str("  if (game.direction === 'right') nx += 1;\n");
    out.push_str("  if (nx <= 0 || nx >= game.width - 1 || ny <= 0 || ny >= game.height - 1) {\n");
    out.push_str("    game.alive = false;\n");
    out.push_str("    dispatch('done');\n");
    out.push_str("    return;\n");
    out.push_str("  }\n");
    out.push_str("  for (const p of game.snake) {\n");
    out.push_str("    if (p.x === nx && p.y === ny) {\n");
    out.push_str("      game.alive = false;\n");
    out.push_str("      dispatch('done');\n");
    out.push_str("      return;\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("  game.snake.unshift({ x: nx, y: ny });\n");
    out.push_str("  const ate = game.food && game.food.x === nx && game.food.y === ny;\n");
    out.push_str("  if (ate) {\n");
    out.push_str("    game.score += 1;\n");
    out.push_str("    game.food = placeFood(game);\n");
    out.push_str("  } else {\n");
    out.push_str("    game.snake.pop();\n");
    out.push_str("  }\n");
    out.push_str("  if (!game.food) {\n");
    out.push_str("    dispatch('done');\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    out.push_str("function renderSnake() {\n");
    out.push_str("  const wall = '██';\n");
    out.push_str("  const empty = '  ';\n");
    out.push_str("  const body = COLORS.green + '▓▓' + RESET;\n");
    out.push_str("  const head = COLORS.yellow + '██' + RESET;\n");
    out.push_str("  const food = COLORS.magenta + '◉ ' + RESET;\n");
    out.push_str("  const border = COLORS.cyan + wall + RESET;\n");
    out.push_str("  const grid = Array.from({ length: game.height }, () => Array.from({ length: game.width }, () => empty));\n");
    out.push_str("  for (let x = 0; x < game.width; x += 1) { grid[0][x] = border; grid[game.height - 1][x] = border; }\n");
    out.push_str("  for (let y = 0; y < game.height; y += 1) { grid[y][0] = border; grid[y][game.width - 1] = border; }\n");
    out.push_str("  if (game.food) grid[game.food.y][game.food.x] = food;\n");
    out.push_str("  for (let i = 0; i < game.snake.length; i += 1) {\n");
    out.push_str("    const p = game.snake[i];\n");
    out.push_str("    grid[p.y][p.x] = i === 0 ? head : body;\n");
    out.push_str("  }\n");
    out.push_str("  const hud = COLORS.cyan + `Score: ${game.score}   Length: ${game.snake.length}   Size: ${game.width - 2}x${game.height - 2}` + RESET;\n");
    out.push_str("  console.log(hud);\n");
    out.push_str("  for (const row of grid) console.log(row.join(''));\n");
    out.push_str("}\n\n");

    out.push_str("function startTicker() {\n");
    out.push_str("  if (tickHandle) return;\n");
    out.push_str("  const ms = game ? game.tickMs : Math.max(20, Number(((EXT.runtime || {}).tickMs) || 80));\n");
    out.push_str("  tickHandle = setInterval(() => {\n");
    out.push_str("    dispatch('input.tick');\n");
    out.push_str("    if (game && game.kind === 'breakout') stepBreakout();\n");
    out.push_str("    if (game && game.kind === 'snake') stepSnake();\n");
    out.push_str("    if (game) render();\n");
    out.push_str("  }, ms);\n");
    out.push_str("}\n\n");

    out.push_str("function stopTicker() {\n");
    out.push_str("  if (tickHandle) {\n");
    out.push_str("    clearInterval(tickHandle);\n");
    out.push_str("    tickHandle = null;\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    out.push_str("function stateNeedsTick(s) {\n");
    out.push_str("  const map = (FLOW.transitions && FLOW.transitions[s]) || {};\n");
    out.push_str("  if (Object.prototype.hasOwnProperty.call(map, 'tick')) return true;\n");
    out.push_str("  if (Object.prototype.hasOwnProperty.call(map, 'input.tick')) return true;\n");
    out.push_str("  for (const rule of RUNTIME_RULES) {\n");
    out.push_str("    if (!rule || (rule.on !== 'tick' && rule.on !== 'input.tick')) continue;\n");
    out.push_str("    if (rule.scopeState && rule.scopeState !== s) continue;\n");
    out.push_str("    return true;\n");
    out.push_str("  }\n");
    out.push_str("  return false;\n");
    out.push_str("}\n\n");

    out.push_str("function parseCsv(text) {\n");
    out.push_str(
        "  const lines = String(text || '').split(/\\r?\\n/).filter((l) => l.length > 0);\n",
    );
    out.push_str("  if (lines.length === 0) return [];\n");
    out.push_str("  const headers = lines[0].split(',').map((h) => h.trim());\n");
    out.push_str("  const rows = [];\n");
    out.push_str("  for (let i = 1; i < lines.length; i += 1) {\n");
    out.push_str("    const cols = lines[i].split(',');\n");
    out.push_str("    const row = {};\n");
    out.push_str("    for (let j = 0; j < headers.length; j += 1) row[headers[j]] = String(cols[j] || '').trim();\n");
    out.push_str("    rows.push(row);\n");
    out.push_str("  }\n");
    out.push_str("  return rows;\n");
    out.push_str("}\n\n");

    out.push_str("function daysDiff(a, b) {\n");
    out.push_str("  const da = new Date(String(a || '') + 'T00:00:00Z');\n");
    out.push_str("  const db = new Date(String(b || '') + 'T00:00:00Z');\n");
    out.push_str("  return Math.round((da.getTime() - db.getTime()) / 86400000);\n");
    out.push_str("}\n\n");

    out.push_str("function approxEq(a, b, tol) {\n");
    out.push_str("  return Math.abs(Number(a || 0) - Number(b || 0)) <= Number(tol || 0);\n");
    out.push_str("}\n\n");

    out.push_str("function runtimeOp(name, args) {\n");
    out.push_str("  const op = String(name || '').split('.').pop();\n");
    out.push_str("  if (op === 'csvRead') {\n");
    out.push_str("    const file = String(args[0] || '');\n");
    out.push_str(
        "    const full = path.isAbsolute(file) ? file : path.resolve(process.cwd(), file);\n",
    );
    out.push_str(
        "    try { return parseCsv(fs.readFileSync(full, 'utf8')); } catch { return []; }\n",
    );
    out.push_str("  }\n");
    out.push_str("  if (op === 'rowCount') return Array.isArray(args[0]) ? args[0].length : 0;\n");
    out.push_str("  if (op === 'csvHasColumns') {\n");
    out.push_str("    const rows = Array.isArray(args[0]) ? args[0] : [];\n");
    out.push_str("    const required = String(args[1] || '').split(',').map((s) => s.trim()).filter(Boolean);\n");
    out.push_str("    if (rows.length === 0) return required.length === 0 ? 1 : 0;\n");
    out.push_str("    const head = rows[0] || {};\n");
    out.push_str("    return required.every((k) => Object.prototype.hasOwnProperty.call(head, k)) ? 1 : 0;\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'csvMissingColumns') {\n");
    out.push_str("    const rows = Array.isArray(args[0]) ? args[0] : [];\n");
    out.push_str("    const required = String(args[1] || '').split(',').map((s) => s.trim()).filter(Boolean);\n");
    out.push_str("    if (required.length === 0) return [];\n");
    out.push_str("    if (rows.length === 0) return required;\n");
    out.push_str("    const head = rows[0] || {};\n");
    out.push_str(
        "    return required.filter((k) => !Object.prototype.hasOwnProperty.call(head, k));\n",
    );
    out.push_str("  }\n");
    out.push_str("  if (op === 'schemaErrorMessage') {\n");
    out.push_str("    const invMissing = Array.isArray(args[0]) ? args[0].map((x) => String(x)).filter(Boolean) : [];\n");
    out.push_str("    const payMissing = Array.isArray(args[1]) ? args[1].map((x) => String(x)).filter(Boolean) : [];\n");
    out.push_str("    const parts = [];\n");
    out.push_str("    if (invMissing.length > 0) parts.push(`invoices.csv missing: ${invMissing.join(', ')}`);\n");
    out.push_str("    if (payMissing.length > 0) parts.push(`payments.csv missing: ${payMissing.join(', ')}`);\n");
    out.push_str("    if (parts.length === 0) return 'Input schema invalid';\n");
    out.push_str("    return `Input schema invalid: ${parts.join(' | ')}`;\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'reconcileInvoices') {\n");
    out.push_str("    const invoices = Array.isArray(args[0]) ? args[0] : [];\n");
    out.push_str("    const payments = Array.isArray(args[1]) ? args[1] : [];\n");
    out.push_str("    const toleranceDays = Number(args[2] || 30);\n");
    out.push_str("    const amountTolerance = Number(args[3] || 0);\n");
    out.push_str("    const startedAt = Date.now();\n");
    out.push_str("    const byInv = new Map();\n");
    out.push_str("    const byCust = new Map();\n");
    out.push_str("    for (const p of payments) {\n");
    out.push_str("      const inv = String(p.invoice_id || '');\n");
    out.push_str("      const cust = String(p.customer_id || '');\n");
    out.push_str("      if (!byInv.has(inv)) byInv.set(inv, []);\n");
    out.push_str("      byInv.get(inv).push(p);\n");
    out.push_str("      if (!byCust.has(cust)) byCust.set(cust, []);\n");
    out.push_str("      byCust.get(cust).push(p);\n");
    out.push_str("    }\n");
    out.push_str("    const usedPayment = new Set();\n");
    out.push_str("    const exceptions = [];\n");
    out.push_str("    const counts = { matched_full: 0, matched_partial: 0, overpaid: 0, missing_payment: 0, duplicate_payment: 0, ambiguous: 0, suspicious: 0 };\n");
    out.push_str("    for (const inv of invoices) {\n");
    out.push_str("      const amountDue = Number(inv.amount_due || 0);\n");
    out.push_str("      const dueDate = String(inv.due_date || '');\n");
    out.push_str("      const invId = String(inv.invoice_id || '');\n");
    out.push_str("      const custId = String(inv.customer_id || '');\n");
    out.push_str("      const direct = (byInv.get(invId) || []).filter((p) => String(p.customer_id || '') === custId);\n");
    out.push_str("      const inWindow = direct.filter((p) => Math.abs(daysDiff(p.payment_date, dueDate)) <= toleranceDays);\n");
    out.push_str("      let candidates = inWindow;\n");
    out.push_str("      if (candidates.length === 0) {\n");
    out.push_str("        const custPool = byCust.get(custId) || [];\n");
    out.push_str("        const fallback = custPool.filter((p) => {\n");
    out.push_str("          const amount = Number(p.amount_paid || 0);\n");
    out.push_str("          return (!p.invoice_id || String(p.invoice_id).length === 0) && approxEq(amount, amountDue, amountTolerance) && Math.abs(daysDiff(p.payment_date, dueDate)) <= toleranceDays;\n");
    out.push_str("        });\n");
    out.push_str("        if (fallback.length === 1) candidates = fallback;\n");
    out.push_str("        if (fallback.length > 1) {\n");
    out.push_str("          counts.ambiguous += 1;\n");
    out.push_str("          exceptions.push({ invoice_id: invId, payment_id: '', classification: 'ambiguous', reason: 'multiple fallback candidates' });\n");
    out.push_str("          continue;\n");
    out.push_str("        }\n");
    out.push_str("      }\n");
    out.push_str("      if (candidates.length === 0) {\n");
    out.push_str("        counts.missing_payment += 1;\n");
    out.push_str("        exceptions.push({ invoice_id: invId, payment_id: '', classification: 'missing_payment', reason: 'no payment found' });\n");
    out.push_str("        continue;\n");
    out.push_str("      }\n");
    out.push_str("      if (candidates.length > 1) {\n");
    out.push_str("        counts.duplicate_payment += 1;\n");
    out.push_str("        exceptions.push({ invoice_id: invId, payment_id: candidates.map((p) => String(p.payment_id || '')).join('|'), classification: 'duplicate_payment', reason: 'multiple payments for one invoice' });\n");
    out.push_str(
        "        for (const p of candidates) usedPayment.add(String(p.payment_id || ''));\n",
    );
    out.push_str("        continue;\n");
    out.push_str("      }\n");
    out.push_str("      const p = candidates[0];\n");
    out.push_str("      usedPayment.add(String(p.payment_id || ''));\n");
    out.push_str("      const amount = Number(p.amount_paid || 0);\n");
    out.push_str("      if (String(p.customer_id || '') !== custId) {\n");
    out.push_str("        counts.suspicious += 1;\n");
    out.push_str("        exceptions.push({ invoice_id: invId, payment_id: String(p.payment_id || ''), classification: 'suspicious', reason: 'customer mismatch' });\n");
    out.push_str("        continue;\n");
    out.push_str("      }\n");
    out.push_str("      if (approxEq(amount, amountDue, amountTolerance)) {\n");
    out.push_str("        counts.matched_full += 1;\n");
    out.push_str("      } else if (amount < amountDue) {\n");
    out.push_str("        counts.matched_partial += 1;\n");
    out.push_str("        exceptions.push({ invoice_id: invId, payment_id: String(p.payment_id || ''), classification: 'matched_partial', reason: `paid ${amount.toFixed(2)} / due ${amountDue.toFixed(2)}` });\n");
    out.push_str("      } else {\n");
    out.push_str("        counts.overpaid += 1;\n");
    out.push_str("        exceptions.push({ invoice_id: invId, payment_id: String(p.payment_id || ''), classification: 'overpaid', reason: `paid ${amount.toFixed(2)} / due ${amountDue.toFixed(2)}` });\n");
    out.push_str("      }\n");
    out.push_str("    }\n");
    out.push_str("    for (const p of payments) {\n");
    out.push_str("      const pid = String(p.payment_id || '');\n");
    out.push_str("      if (usedPayment.has(pid)) continue;\n");
    out.push_str("      if (!p.invoice_id) {\n");
    out.push_str("        counts.suspicious += 1;\n");
    out.push_str("        exceptions.push({ invoice_id: '', payment_id: pid, classification: 'suspicious', reason: 'unmatched payment without invoice_id' });\n");
    out.push_str("        continue;\n");
    out.push_str("      }\n");
    out.push_str("      const exists = invoices.some((i) => String(i.invoice_id || '') === String(p.invoice_id || ''));\n");
    out.push_str("      if (!exists) {\n");
    out.push_str("        counts.suspicious += 1;\n");
    out.push_str("        exceptions.push({ invoice_id: String(p.invoice_id || ''), payment_id: pid, classification: 'suspicious', reason: 'references unknown invoice' });\n");
    out.push_str("      }\n");
    out.push_str("    }\n");
    out.push_str("    return { counts, exceptions, processing_ms: Date.now() - startedAt };\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'metric') {\n");
    out.push_str("    const rec = args[0] && typeof args[0] === 'object' ? args[0] : {};\n");
    out.push_str("    const key = String(args[1] || '');\n");
    out.push_str("    return Number((((rec.counts || {})[key]) || 0));\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'buildExceptions') {\n");
    out.push_str("    const rec = args[0] && typeof args[0] === 'object' ? args[0] : {};\n");
    out.push_str("    return Array.isArray(rec.exceptions) ? rec.exceptions.slice() : [];\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'buildReportJson') {\n");
    out.push_str("    return {\n");
    out.push_str(
        "      input_stats: { invoices: Number(args[0] || 0), payments: Number(args[1] || 0) },\n",
    );
    out.push_str("      classification_counts: {\n");
    out.push_str("        matched_full: Number(args[2] || 0), matched_partial: Number(args[3] || 0), overpaid: Number(args[4] || 0), missing_payment: Number(args[5] || 0), duplicate_payment: Number(args[6] || 0), ambiguous: Number(args[7] || 0), suspicious: Number(args[8] || 0)\n");
    out.push_str("      },\n");
    out.push_str("      rules_version: String(args[9] || '1.0'),\n");
    out.push_str("      processing_ms: Number(args[10] || 0),\n");
    out.push_str("      generated_at: new Date().toISOString()\n");
    out.push_str("    };\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'processingMs') {\n");
    out.push_str("    const rec = args[0] && typeof args[0] === 'object' ? args[0] : {};\n");
    out.push_str("    return Number(rec.processing_ms || 0);\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'writeJson') {\n");
    out.push_str("    try {\n");
    out.push_str("      const file = String(args[0] || '');\n");
    out.push_str(
        "      const full = path.isAbsolute(file) ? file : path.resolve(process.cwd(), file);\n",
    );
    out.push_str("      fs.mkdirSync(path.dirname(full), { recursive: true });\n");
    out.push_str(
        "      fs.writeFileSync(full, JSON.stringify(args[1] || {}, null, 2) + '\\n', 'utf8');\n",
    );
    out.push_str("      return 1;\n");
    out.push_str("    } catch { return 0; }\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'sortBy') {\n");
    out.push_str("    const rows = Array.isArray(args[0]) ? args[0].slice() : [];\n");
    out.push_str(
        "    const keys = String(args[1] || '').split(',').map((k) => k.trim()).filter(Boolean);\n",
    );
    out.push_str("    rows.sort((a, b) => {\n");
    out.push_str("      for (const k of keys) {\n");
    out.push_str("        const av = String((a && a[k]) || '');\n");
    out.push_str("        const bv = String((b && b[k]) || '');\n");
    out.push_str("        if (av < bv) return -1;\n");
    out.push_str("        if (av > bv) return 1;\n");
    out.push_str("      }\n");
    out.push_str("      return 0;\n");
    out.push_str("    });\n");
    out.push_str("    return rows;\n");
    out.push_str("  }\n");
    out.push_str("  if (op === 'writeCsv') {\n");
    out.push_str("    try {\n");
    out.push_str("      const file = String(args[0] || '');\n");
    out.push_str(
        "      const full = path.isAbsolute(file) ? file : path.resolve(process.cwd(), file);\n",
    );
    out.push_str("      fs.mkdirSync(path.dirname(full), { recursive: true });\n");
    out.push_str("      const rows = Array.isArray(args[1]) ? args[1] : [];\n");
    out.push_str("      const header = ['invoice_id','payment_id','classification','reason'];\n");
    out.push_str("      const lines = [header.join(',')];\n");
    out.push_str("      for (const row of rows) {\n");
    out.push_str("        const vals = header.map((k) => String((row && row[k]) || '').replace(/,/g, ';'));\n");
    out.push_str("        lines.push(vals.join(','));\n");
    out.push_str("      }\n");
    out.push_str("      fs.writeFileSync(full, lines.join('\\n') + '\\n', 'utf8');\n");
    out.push_str("      return 1;\n");
    out.push_str("    } catch { return 0; }\n");
    out.push_str("  }\n");
    out.push_str(
        "  if (op === 'summaryLine') return `${String(args[0] || '')}: ${Number(args[1] || 0)}`;\n",
    );
    out.push_str("  return null;\n");
    out.push_str("}\n\n");

    out.push_str("function evalBinaryExpr(node) {\n");
    out.push_str("  if (!node || typeof node !== 'object') return null;\n");
    out.push_str("  const op = String(node.op || '');\n");
    out.push_str("  const left = resolveRuntimeValue(node.left);\n");
    out.push_str("  const right = resolveRuntimeValue(node.right);\n");
    out.push_str("  if (op === 'Add') return Number(left || 0) + Number(right || 0);\n");
    out.push_str("  if (op === 'Sub') return Number(left || 0) - Number(right || 0);\n");
    out.push_str("  if (op === 'Mul') return Number(left || 0) * Number(right || 0);\n");
    out.push_str("  if (op === 'Div') return Number(right || 0) === 0 ? 0 : Number(left || 0) / Number(right || 1);\n");
    out.push_str("  if (op === 'And') return (left ? 1 : 0) && (right ? 1 : 0) ? 1 : 0;\n");
    out.push_str("  if (op === 'Or') return (left ? 1 : 0) || (right ? 1 : 0) ? 1 : 0;\n");
    out.push_str("  if (op === 'Eq') return left === right ? 1 : 0;\n");
    out.push_str("  if (op === 'Neq') return left !== right ? 1 : 0;\n");
    out.push_str("  if (op === 'Gt') return Number(left || 0) > Number(right || 0) ? 1 : 0;\n");
    out.push_str("  if (op === 'Gte') return Number(left || 0) >= Number(right || 0) ? 1 : 0;\n");
    out.push_str("  if (op === 'Lt') return Number(left || 0) < Number(right || 0) ? 1 : 0;\n");
    out.push_str("  if (op === 'Lte') return Number(left || 0) <= Number(right || 0) ? 1 : 0;\n");
    out.push_str("  return null;\n");
    out.push_str("}\n\n");

    out.push_str("function resolveRuntimeValue(v) {\n");
    out.push_str("  if (v && typeof v === 'object' && !Array.isArray(v)) {\n");
    out.push_str("    if (typeof v.ident === 'string') return RUNTIME_STATE[v.ident];\n");
    out.push_str(
        "    if (v.binary && typeof v.binary === 'object') return evalBinaryExpr(v.binary);\n",
    );
    out.push_str("    if (v.call && typeof v.call === 'object') {\n");
    out.push_str("      const callName = String(v.call.name || '');\n");
    out.push_str("      const rawArgs = Array.isArray(v.call.args) ? v.call.args : [];\n");
    out.push_str("      const args = rawArgs.map((a) => resolveRuntimeValue(a && typeof a === 'object' ? a.value : null));\n");
    out.push_str("      return runtimeOp(callName, args);\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("  return v;\n");
    out.push_str("}\n\n");

    out.push_str("function evalWhen(when) {\n");
    out.push_str("  if (!when || typeof when !== 'object') return false;\n");
    out.push_str("  if (when.kind === 'logic') {\n");
    out.push_str(
        "    if (when.op === 'and') return evalWhen(when.left) && evalWhen(when.right);\n",
    );
    out.push_str("    if (when.op === 'or') return evalWhen(when.left) || evalWhen(when.right);\n");
    out.push_str("    return false;\n");
    out.push_str("  }\n");
    out.push_str("  const mode = when.kind === 'cmp' ? when.op : when.op;\n");
    out.push_str("  if (mode === 'gte') {\n");
    out.push_str("    const left = Number(RUNTIME_STATE[String(when.left)] || 0);\n");
    out.push_str("    const right = Number(resolveRuntimeValue(when.right) || 0);\n");
    out.push_str("    return left >= right;\n");
    out.push_str("  }\n");
    out.push_str("  if (mode === 'gt') {\n");
    out.push_str("    const left = Number(RUNTIME_STATE[String(when.left)] || 0);\n");
    out.push_str("    const right = Number(resolveRuntimeValue(when.right) || 0);\n");
    out.push_str("    return left > right;\n");
    out.push_str("  }\n");
    out.push_str("  if (mode === 'lt') {\n");
    out.push_str("    const left = Number(RUNTIME_STATE[String(when.left)] || 0);\n");
    out.push_str("    const right = Number(resolveRuntimeValue(when.right) || 0);\n");
    out.push_str("    return left < right;\n");
    out.push_str("  }\n");
    out.push_str("  if (mode === 'eq') {\n");
    out.push_str("    const left = RUNTIME_STATE[String(when.left)];\n");
    out.push_str("    const right = resolveRuntimeValue(when.right);\n");
    out.push_str("    if (typeof left === 'number' || typeof right === 'number') {\n");
    out.push_str("      return Number(left || 0) === Number(right || 0);\n");
    out.push_str("    }\n");
    out.push_str("    return String(left) === String(right);\n");
    out.push_str("  }\n");
    out.push_str("  if (mode === 'neq') {\n");
    out.push_str("    const left = RUNTIME_STATE[String(when.left)];\n");
    out.push_str("    const right = resolveRuntimeValue(when.right);\n");
    out.push_str("    if (typeof left === 'number' || typeof right === 'number') {\n");
    out.push_str("      return Number(left || 0) !== Number(right || 0);\n");
    out.push_str("    }\n");
    out.push_str("    return String(left) !== String(right);\n");
    out.push_str("  }\n");
    out.push_str("  return false;\n");
    out.push_str("}\n\n");

    out.push_str("function applyRuntimeRules(event, firedWhen) {\n");
    out.push_str("  const emitted = [];\n");
    out.push_str("  for (const rule of RUNTIME_RULES) {\n");
    out.push_str("    if (!rule) continue;\n");
    out.push_str("    if (rule.scopeState && rule.scopeState !== state) continue;\n");
    out.push_str("    const isOnRule = typeof rule.on === 'string' && rule.on.length > 0;\n");
    out.push_str("    const isWhenRule = !!rule.when;\n");
    out.push_str("    if (isOnRule && rule.on !== event) continue;\n");
    out.push_str("    if (!isOnRule && isWhenRule && event !== 'tick' && event !== 'input.tick') continue;\n");
    out.push_str("    if (isWhenRule) {\n");
    out.push_str("      if (firedWhen && firedWhen.has(rule.name)) continue;\n");
    out.push_str("      if (!evalWhen(rule.when)) continue;\n");
    out.push_str("      if (firedWhen) firedWhen.add(rule.name);\n");
    out.push_str("    }\n");
    out.push_str("    if (!isOnRule && !isWhenRule) continue;\n");
    out.push_str("    const assigns = Array.isArray(rule.assign) ? rule.assign : [];\n");
    out.push_str("    for (const a of assigns) {\n");
    out.push_str("      if (!a || typeof a.target !== 'string') continue;\n");
    out.push_str("      const value = resolveRuntimeValue(a.value);\n");
    out.push_str("      if (a.op === 'add') {\n");
    out.push_str("        const cur = Number(RUNTIME_STATE[a.target] || 0);\n");
    out.push_str("        const add = Number(value || 0);\n");
    out.push_str("        RUNTIME_STATE[a.target] = cur + add;\n");
    out.push_str("      } else {\n");
    out.push_str("        RUNTIME_STATE[a.target] = value;\n");
    out.push_str("      }\n");
    out.push_str("    }\n");
    out.push_str("    const emits = Array.isArray(rule.emit) ? rule.emit : [];\n");
    out.push_str("    for (const ev of emits) {\n");
    out.push_str("      if (typeof ev === 'string' && ev.length > 0) emitted.push(ev);\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("  return emitted;\n");
    out.push_str("}\n\n");

    out.push_str("function render() {\n");
    out.push_str("  console.clear();\n");
    out.push_str("  if (game && state === 'Play') {\n");
    out.push_str("    if (game.kind === 'breakout') renderBreakout();\n");
    out.push_str("    if (game.kind === 'snake') renderSnake();\n");
    out.push_str("    return;\n");
    out.push_str("  }\n");
    out.push_str("  const items = VIEWS[state] || [];\n");
    out.push_str("  for (const item of items) {\n");
    out.push_str("    if (item.kind === 'text') {\n");
    out.push_str("      const color = item.color ? (COLORS[item.color] || '') : '';\n");
    out.push_str("      const raw = item.text || '';\n");
    out.push_str("      const txt = (typeof raw === 'string' && Object.prototype.hasOwnProperty.call(RUNTIME_STATE, raw)) ? String(RUNTIME_STATE[raw]) : String(raw);\n");
    out.push_str("      console.log(color + txt + RESET);\n");
    out.push_str("    }\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    out.push_str("function processEvent(event, depth, firedWhen) {\n");
    out.push_str("  if (depth > 24) return;\n");
    out.push_str("  if (!firedWhen) firedWhen = new Set();\n");
    out.push_str("  const before = state;\n");
    out.push_str("  if (game) handleGameInput(event);\n");
    out.push_str("  const map = (FLOW.transitions && FLOW.transitions[state]) || {};\n");
    out.push_str("  if (map[event]) state = map[event];\n");
    out.push_str("  const emitted = applyRuntimeRules(event, firedWhen);\n");
    out.push_str("  if (state !== before && state === 'Play') {\n");
    out.push_str("    enterPlayState();\n");
    out.push_str("  }\n");
    out.push_str("  if (stateNeedsTick(state)) {\n");
    out.push_str("    startTicker();\n");
    out.push_str("  } else {\n");
    out.push_str("    stopTicker();\n");
    out.push_str("  }\n");
    out.push_str(
        "  if (state !== before && String(state).toLowerCase() === 'exit') process.exit(0);\n",
    );
    out.push_str("  if (state !== before) render();\n");
    out.push_str("  for (const ev of emitted) processEvent(ev, depth + 1, firedWhen);\n");
    out.push_str("}\n\n");

    out.push_str("function dispatch(event) {\n");
    out.push_str("  processEvent(event, 0, new Set());\n");
    out.push_str("}\n\n");

    out.push_str("function normalizeKey(key) {\n");
    out.push_str("  if (key === '\\r' || key === '\\n' || key.includes('\\r') || key.includes('\\n')) return 'enter';\n");
    out.push_str("  if (key === '\\u001b') return 'esc';\n");
    out.push_str("  if (key === '\\u001b[A') return 'up';\n");
    out.push_str("  if (key === '\\u001b[B') return 'down';\n");
    out.push_str("  if (key === '\\u001b[D') return 'left';\n");
    out.push_str("  if (key === '\\u001b[C') return 'right';\n");
    out.push_str("  if (key === ' ') return 'space';\n");
    out.push_str("  return key.trim().toLowerCase();\n");
    out.push_str("}\n\n");

    out.push_str("ensureGameInit();\n");
    out.push_str("if (stateNeedsTick(state)) startTicker();\n");
    out.push_str("render();\n");
    out.push_str("if (process.stdin.isTTY) process.stdin.setRawMode(true);\n");
    out.push_str("process.stdin.resume();\n");
    out.push_str("process.stdin.on('data', (buf) => {\n");
    out.push_str("  const key = buf.toString('utf8');\n");
    out.push_str("  if (key === '\\u0003') process.exit(0);\n");
    out.push_str("  const k = normalizeKey(key);\n");
    out.push_str("  dispatch(`key(${k})`);\n");
    out.push_str("});\n");

    out
}
