use crate::target_ir::TargetIr;

pub fn generate_web_js(target: &TargetIr) -> String {
  let mut out = String::new();
  let target_json = serde_json::to_string(target).unwrap_or_else(|_| "{}".to_string());

  out.push_str("// Auto-generated by sculpt (web)\n\n");
  out.push_str(&format!("const TARGET = {};\n\n", target_json));
  out.push_str("const VIEWS = TARGET.views || {};\n");
  out.push_str("const FLOW = TARGET.flow || { start: '', transitions: {} };\n");
  out.push_str("let state = FLOW.start || '';\n\n");

  out.push_str("function applyRender() {\n");
  out.push_str("  const root = document.getElementById('app');\n");
  out.push_str("  if (!root) return;\n");
  out.push_str("  root.innerHTML = '';\n");
  out.push_str("  const items = VIEWS[state] || [];\n");
  out.push_str("  for (const item of items) {\n");
  out.push_str("    if (item.kind === 'text') {\n");
  out.push_str("      const span = document.createElement('span');\n");
  out.push_str("      span.textContent = item.text || '';\n");
  out.push_str("      if (item.color) span.style.color = item.color;\n");
  out.push_str("      if (item.css && typeof item.css === 'object') {\n");
  out.push_str("        Object.assign(span.style, item.css);\n");
  out.push_str("      }\n");
  out.push_str("      root.appendChild(span);\n");
  out.push_str("      root.appendChild(document.createElement('br'));\n");
  out.push_str("    }\n");
  out.push_str("  }\n");
  out.push_str("}\n\n");

  out.push_str("function dispatch(event) {\n");
  out.push_str("  const before = state;\n");
  out.push_str("  const map = (FLOW.transitions && FLOW.transitions[state]) || {};\n");
  out.push_str("  if (map[event]) state = map[event];\n");
  out.push_str("  if (state !== before) applyRender();\n");
  out.push_str("}\n\n");

  out.push_str("function normalizeKey(key) {\n");
  out.push_str("  if (key === '\\r') return 'enter';\n");
  out.push_str("  if (key === '\\u001b') return 'esc';\n");
  out.push_str("  if (key === ' ') return 'space';\n");
  out.push_str("  return key.trim().toLowerCase();\n");
  out.push_str("}\n\n");

  out.push_str("window.addEventListener('DOMContentLoaded', () => {\n");
  out.push_str("  applyRender();\n");
  out.push_str("  window.addEventListener('keydown', (e) => {\n");
  out.push_str("    const key = normalizeKey(e.key);\n");
  out.push_str("    const ev = `key(${key})`;\n");
  out.push_str("    dispatch(ev);\n");
  out.push_str("  });\n");
  out.push_str("});\n");

  out
}
